ALTER TABLE "User" ADD COLUMN "emailScoringEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "emailDraftEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "emailLeagueEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "emailSecurityEnabled" BOOLEAN NOT NULL DEFAULT true;
